// Comprehensive Built-in Food & Nutrition Database
// Serving sizes standardized with nutritional values per unit/weight

export const FOOD_DATABASE = [
  // --- PROTEINS & MEATS ---
  {
    id: "egg_boiled",
    names: ["egg", "boiled egg", "hard boiled egg", "eggs", "boiled eggs"],
    category: "protein",
    defaultUnit: "egg",
    servingWeightG: 50,
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
    potassium: 63,
    calcium: 25,
    iron: 0.6,
    vitaminA: 260,
    vitaminC: 0
  },
  {
    id: "egg_fried",
    names: ["fried egg", "sunny side up egg", "scrambled egg", "fried eggs", "scrambled eggs"],
    category: "protein",
    defaultUnit: "egg",
    servingWeightG: 55,
    calories: 90,
    protein: 6.3,
    carbs: 0.7,
    fat: 7.0,
    fiber: 0,
    sugar: 0.4,
    sodium: 95,
    potassium: 70,
    calcium: 28,
    iron: 0.9,
    vitaminA: 280,
    vitaminC: 0
  },
  {
    id: "egg_white",
    names: ["egg white", "egg whites"],
    category: "protein",
    defaultUnit: "egg white",
    servingWeightG: 33,
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fat: 0.1,
    fiber: 0,
    sugar: 0.2,
    sodium: 55,
    potassium: 54,
    calcium: 2,
    iron: 0.1,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "chicken_breast",
    names: ["chicken breast", "grilled chicken", "boiled chicken", "baked chicken", "chicken"],
    category: "protein",
    defaultUnit: "g",
    servingWeightG: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    potassium: 256,
    calcium: 15,
    iron: 1.0,
    vitaminA: 35,
    vitaminC: 0
  },
  {
    id: "chicken_curry",
    names: ["chicken curry", "butter chicken", "chicken tikka masala"],
    category: "protein",
    defaultUnit: "cup",
    servingWeightG: 200,
    calories: 320,
    protein: 26.0,
    carbs: 9.0,
    fat: 20.0,
    fiber: 2.0,
    sugar: 3.5,
    sodium: 540,
    potassium: 380,
    calcium: 45,
    iron: 2.2,
    vitaminA: 150,
    vitaminC: 4
  },
  {
    id: "salmon",
    names: ["salmon", "grilled salmon", "baked salmon", "salmon fillet"],
    category: "protein",
    defaultUnit: "g",
    servingWeightG: 100,
    calories: 208,
    protein: 22.0,
    carbs: 0.0,
    fat: 13.0,
    fiber: 0,
    sugar: 0,
    sodium: 59,
    potassium: 363,
    calcium: 9,
    iron: 0.5,
    vitaminA: 140,
    vitaminC: 0
  },
  {
    id: "tuna_canned",
    names: ["tuna", "canned tuna", "tuna in water"],
    category: "protein",
    defaultUnit: "can",
    servingWeightG: 140,
    calories: 150,
    protein: 33.0,
    carbs: 0.0,
    fat: 1.5,
    fiber: 0,
    sugar: 0,
    sodium: 350,
    potassium: 320,
    calcium: 12,
    iron: 1.8,
    vitaminA: 40,
    vitaminC: 0
  },
  {
    id: "paneer",
    names: ["paneer", "cottage cheese", "paneer cubes", "raw paneer"],
    category: "protein",
    defaultUnit: "g",
    servingWeightG: 100,
    calories: 265,
    protein: 18.3,
    carbs: 3.5,
    fat: 20.8,
    fiber: 0,
    sugar: 2.5,
    sodium: 22,
    potassium: 110,
    calcium: 480,
    iron: 0.4,
    vitaminA: 180,
    vitaminC: 0
  },
  {
    id: "tofu",
    names: ["tofu", "firm tofu", "steamed tofu"],
    category: "protein",
    defaultUnit: "g",
    servingWeightG: 100,
    calories: 83,
    protein: 10.0,
    carbs: 2.3,
    fat: 5.3,
    fiber: 1.2,
    sugar: 0.6,
    sodium: 14,
    potassium: 150,
    calcium: 350,
    iron: 2.7,
    vitaminA: 85,
    vitaminC: 0
  },
  {
    id: "whey_protein",
    names: ["whey protein", "protein powder", "protein shake", "whey scoop", "scoop of protein"],
    category: "protein",
    defaultUnit: "scoop",
    servingWeightG: 30,
    calories: 120,
    protein: 24.0,
    carbs: 2.5,
    fat: 1.5,
    fiber: 0.5,
    sugar: 1.0,
    sodium: 140,
    potassium: 160,
    calcium: 140,
    iron: 0.5,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "lentils_cooked",
    names: ["lentils", "dal", "yellow dal", "cooked dal", "tadka dal", "lentil soup"],
    category: "protein",
    defaultUnit: "bowl",
    servingWeightG: 200,
    calories: 180,
    protein: 12.0,
    carbs: 28.0,
    fat: 3.5,
    fiber: 7.8,
    sugar: 1.8,
    sodium: 320,
    potassium: 365,
    calcium: 38,
    iron: 3.3,
    vitaminA: 40,
    vitaminC: 2
  },
  {
    id: "chickpeas_cooked",
    names: ["chickpeas", "chole", "garbanzo beans", "boiled chickpeas"],
    category: "protein",
    defaultUnit: "cup",
    servingWeightG: 160,
    calories: 269,
    protein: 14.5,
    carbs: 45.0,
    fat: 4.2,
    fiber: 12.5,
    sugar: 7.9,
    sodium: 240,
    potassium: 477,
    calcium: 80,
    iron: 4.7,
    vitaminA: 44,
    vitaminC: 2.1
  },

  // --- GRAINS, BREADS & CARBS ---
  {
    id: "rice_white_cooked",
    names: ["white rice", "steamed rice", "cooked rice", "rice", "bowl of rice"],
    category: "carbs",
    defaultUnit: "cup",
    servingWeightG: 158,
    calories: 206,
    protein: 4.3,
    carbs: 45.0,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0.1,
    sodium: 2,
    potassium: 55,
    calcium: 16,
    iron: 1.9,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "rice_brown_cooked",
    names: ["brown rice", "cooked brown rice"],
    category: "carbs",
    defaultUnit: "cup",
    servingWeightG: 150,
    calories: 180,
    protein: 4.0,
    carbs: 38.0,
    fat: 1.5,
    fiber: 3.2,
    sugar: 0.4,
    sodium: 4,
    potassium: 120,
    calcium: 20,
    iron: 1.0,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "oatmeal_cooked",
    names: ["oatmeal", "oats", "rolled oats", "porridge", "bowl of oats"],
    category: "carbs",
    defaultUnit: "bowl",
    servingWeightG: 234,
    calories: 158,
    protein: 6.0,
    carbs: 27.0,
    fat: 3.2,
    fiber: 4.0,
    sugar: 1.1,
    sodium: 115,
    potassium: 143,
    calcium: 84,
    iron: 2.1,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "bread_whole_wheat",
    names: ["whole wheat bread", "brown bread", "slice of whole wheat bread", "whole grain bread", "wheat bread"],
    category: "carbs",
    defaultUnit: "slice",
    servingWeightG: 35,
    calories: 82,
    protein: 4.0,
    carbs: 14.0,
    fat: 1.1,
    fiber: 2.0,
    sugar: 1.5,
    sodium: 140,
    potassium: 75,
    calcium: 30,
    iron: 0.9,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "bread_white",
    names: ["white bread", "bread slice", "slice of bread", "toast", "white toast"],
    category: "carbs",
    defaultUnit: "slice",
    servingWeightG: 30,
    calories: 79,
    protein: 2.7,
    carbs: 15.0,
    fat: 1.0,
    fiber: 0.8,
    sugar: 1.6,
    sodium: 150,
    potassium: 35,
    calcium: 45,
    iron: 0.8,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "roti_chapati",
    names: ["roti", "chapati", "fulka", "phulka", "rotis", "chapatis"],
    category: "carbs",
    defaultUnit: "piece",
    servingWeightG: 40,
    calories: 104,
    protein: 3.1,
    carbs: 20.0,
    fat: 1.5,
    fiber: 2.5,
    sugar: 0.5,
    sodium: 85,
    potassium: 90,
    calcium: 15,
    iron: 1.2,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "pasta_cooked",
    names: ["pasta", "spaghetti", "macaroni", "penne pasta", "cooked pasta"],
    category: "carbs",
    defaultUnit: "cup",
    servingWeightG: 140,
    calories: 220,
    protein: 8.0,
    carbs: 43.0,
    fat: 1.3,
    fiber: 2.5,
    sugar: 0.8,
    sodium: 1,
    potassium: 60,
    calcium: 10,
    iron: 1.8,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "potato_boiled",
    names: ["boiled potato", "potato", "baked potato", "potatoes"],
    category: "carbs",
    defaultUnit: "medium",
    servingWeightG: 150,
    calories: 130,
    protein: 3.0,
    carbs: 30.0,
    fat: 0.2,
    fiber: 2.8,
    sugar: 1.2,
    sodium: 10,
    potassium: 620,
    calcium: 20,
    iron: 1.1,
    vitaminA: 10,
    vitaminC: 22
  },
  {
    id: "sweet_potato",
    names: ["sweet potato", "baked sweet potato", "boiled sweet potato"],
    category: "carbs",
    defaultUnit: "medium",
    servingWeightG: 130,
    calories: 112,
    protein: 2.0,
    carbs: 26.0,
    fat: 0.1,
    fiber: 3.9,
    sugar: 5.4,
    sodium: 72,
    potassium: 438,
    calcium: 38,
    iron: 0.8,
    vitaminA: 14187,
    vitaminC: 18
  },
  {
    id: "quinoa_cooked",
    names: ["quinoa", "cooked quinoa"],
    category: "carbs",
    defaultUnit: "cup",
    servingWeightG: 185,
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fat: 3.6,
    fiber: 5.2,
    sugar: 1.6,
    sodium: 13,
    potassium: 318,
    calcium: 31,
    iron: 2.8,
    vitaminA: 9,
    vitaminC: 0
  },

  // --- FRUITS & VEGETABLES ---
  {
    id: "banana",
    names: ["banana", "bananas", "ripe banana", "medium banana"],
    category: "fruits",
    defaultUnit: "medium",
    servingWeightG: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14.4,
    sodium: 1,
    potassium: 422,
    calcium: 6,
    iron: 0.3,
    vitaminA: 75,
    vitaminC: 10.3
  },
  {
    id: "apple",
    names: ["apple", "apples", "red apple", "green apple", "medium apple"],
    category: "fruits",
    defaultUnit: "medium",
    servingWeightG: 182,
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    sugar: 19.0,
    sodium: 2,
    potassium: 195,
    calcium: 11,
    iron: 0.2,
    vitaminA: 98,
    vitaminC: 8.4
  },
  {
    id: "orange",
    names: ["orange", "oranges"],
    category: "fruits",
    defaultUnit: "medium",
    servingWeightG: 131,
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    sugar: 12.2,
    sodium: 0,
    potassium: 237,
    calcium: 52,
    iron: 0.1,
    vitaminA: 295,
    vitaminC: 69.7
  },
  {
    id: "berries",
    names: ["berries", "blueberries", "strawberries", "raspberries", "mixed berries"],
    category: "fruits",
    defaultUnit: "cup",
    servingWeightG: 150,
    calories: 75,
    protein: 1.2,
    carbs: 17.5,
    fat: 0.5,
    fiber: 5.0,
    sugar: 10.5,
    sodium: 1,
    potassium: 180,
    calcium: 22,
    iron: 0.6,
    vitaminA: 80,
    vitaminC: 45
  },
  {
    id: "mango",
    names: ["mango", "mango slices", "ripe mango"],
    category: "fruits",
    defaultUnit: "cup",
    servingWeightG: 165,
    calories: 99,
    protein: 1.4,
    carbs: 24.7,
    fat: 0.6,
    fiber: 2.6,
    sugar: 22.5,
    sodium: 2,
    potassium: 277,
    calcium: 18,
    iron: 0.2,
    vitaminA: 1780,
    vitaminC: 60.1
  },
  {
    id: "avocado",
    names: ["avocado", "half avocado", "whole avocado"],
    category: "fruits",
    defaultUnit: "medium",
    servingWeightG: 150,
    calories: 240,
    protein: 3.0,
    carbs: 12.8,
    fat: 22.0,
    fiber: 10.0,
    sugar: 1.0,
    sodium: 10,
    potassium: 730,
    calcium: 18,
    iron: 0.8,
    vitaminA: 215,
    vitaminC: 15
  },
  {
    id: "spinach",
    names: ["spinach", "palak", "cooked spinach", "raw spinach"],
    category: "vegetables",
    defaultUnit: "cup",
    servingWeightG: 100,
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    potassium: 558,
    calcium: 99,
    iron: 2.7,
    vitaminA: 9377,
    vitaminC: 28.1
  },
  {
    id: "broccoli",
    names: ["broccoli", "steamed broccoli", "cooked broccoli"],
    category: "vegetables",
    defaultUnit: "cup",
    servingWeightG: 100,
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 33,
    potassium: 316,
    calcium: 47,
    iron: 0.7,
    vitaminA: 623,
    vitaminC: 89.2
  },
  {
    id: "mixed_salad",
    names: ["salad", "green salad", "mixed salad", "cucumber and tomato salad"],
    category: "vegetables",
    defaultUnit: "bowl",
    servingWeightG: 150,
    calories: 45,
    protein: 1.8,
    carbs: 8.5,
    fat: 0.5,
    fiber: 3.2,
    sugar: 3.8,
    sodium: 40,
    potassium: 320,
    calcium: 42,
    iron: 1.2,
    vitaminA: 1200,
    vitaminC: 24
  },

  // --- DAIRY & BEVERAGES ---
  {
    id: "milk_whole",
    names: ["milk", "whole milk", "glass of milk", "full fat milk"],
    category: "dairy",
    defaultUnit: "glass",
    servingWeightG: 240,
    calories: 149,
    protein: 7.7,
    carbs: 11.7,
    fat: 8.0,
    fiber: 0,
    sugar: 12.3,
    sodium: 105,
    potassium: 322,
    calcium: 276,
    iron: 0.1,
    vitaminA: 395,
    vitaminC: 0
  },
  {
    id: "milk_skimmed",
    names: ["skim milk", "low fat milk", "toned milk", "skimmed milk"],
    category: "dairy",
    defaultUnit: "glass",
    servingWeightG: 240,
    calories: 90,
    protein: 8.3,
    carbs: 12.2,
    fat: 0.6,
    fiber: 0,
    sugar: 12.5,
    sodium: 125,
    potassium: 380,
    calcium: 300,
    iron: 0.1,
    vitaminA: 500,
    vitaminC: 0
  },
  {
    id: "greek_yogurt",
    names: ["greek yogurt", "curd", "plain yogurt", "dahi", "yogurt"],
    category: "dairy",
    defaultUnit: "cup",
    servingWeightG: 170,
    calories: 130,
    protein: 15.0,
    carbs: 6.0,
    fat: 4.5,
    fiber: 0,
    sugar: 5.5,
    sodium: 65,
    potassium: 240,
    calcium: 180,
    iron: 0.1,
    vitaminA: 100,
    vitaminC: 0
  },
  {
    id: "cheese_cheddar",
    names: ["cheese", "cheddar cheese", "slice of cheese", "cheese slice"],
    category: "dairy",
    defaultUnit: "slice",
    servingWeightG: 28,
    calories: 113,
    protein: 7.0,
    carbs: 0.4,
    fat: 9.3,
    fiber: 0,
    sugar: 0.1,
    sodium: 174,
    potassium: 27,
    calcium: 200,
    iron: 0.2,
    vitaminA: 284,
    vitaminC: 0
  },
  {
    id: "coffee_black",
    names: ["black coffee", "espresso", "americano", "black tea", "green tea", "cup of black coffee"],
    category: "beverages",
    defaultUnit: "cup",
    servingWeightG: 240,
    calories: 2,
    protein: 0.3,
    carbs: 0.2,
    fat: 0.0,
    fiber: 0,
    sugar: 0,
    sodium: 5,
    potassium: 116,
    calcium: 5,
    iron: 0.1,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "coffee_with_milk",
    names: ["coffee", "latte", "cappuccino", "coffee with milk", "tea with milk", "chai", "milk tea"],
    category: "beverages",
    defaultUnit: "cup",
    servingWeightG: 200,
    calories: 85,
    protein: 3.5,
    carbs: 9.0,
    fat: 3.5,
    fiber: 0,
    sugar: 8.0,
    sodium: 60,
    potassium: 160,
    calcium: 120,
    iron: 0.2,
    vitaminA: 120,
    vitaminC: 0
  },
  {
    id: "orange_juice",
    names: ["orange juice", "fresh orange juice", "fruit juice"],
    category: "beverages",
    defaultUnit: "glass",
    servingWeightG: 240,
    calories: 112,
    protein: 1.7,
    carbs: 25.8,
    fat: 0.5,
    fiber: 0.5,
    sugar: 20.8,
    sodium: 2,
    potassium: 496,
    calcium: 27,
    iron: 0.5,
    vitaminA: 496,
    vitaminC: 124
  },

  // --- NUTS, SEEDS & FATS ---
  {
    id: "almonds",
    names: ["almonds", "handful of almonds", "soaked almonds", "almond"],
    category: "nuts",
    defaultUnit: "handful",
    servingWeightG: 28,
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.2,
    fiber: 3.5,
    sugar: 1.2,
    sodium: 1,
    potassium: 208,
    calcium: 76,
    iron: 1.0,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "peanut_butter",
    names: ["peanut butter", "tbsp peanut butter", "tablespoon peanut butter"],
    category: "nuts",
    defaultUnit: "tbsp",
    servingWeightG: 32,
    calories: 188,
    protein: 8.0,
    carbs: 6.3,
    fat: 16.0,
    fiber: 1.9,
    sugar: 3.0,
    sodium: 147,
    potassium: 208,
    calcium: 17,
    iron: 0.6,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "walnuts",
    names: ["walnuts", "walnut", "handful of walnuts"],
    category: "nuts",
    defaultUnit: "handful",
    servingWeightG: 28,
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fat: 18.5,
    fiber: 1.9,
    sugar: 0.7,
    sodium: 1,
    potassium: 125,
    calcium: 28,
    iron: 0.8,
    vitaminA: 6,
    vitaminC: 0.4
  },
  {
    id: "olive_oil",
    names: ["olive oil", "oil", "cooking oil", "butter", "ghee", "tbsp oil", "tbsp butter", "tbsp ghee"],
    category: "fats",
    defaultUnit: "tbsp",
    servingWeightG: 14,
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    potassium: 0,
    calcium: 0,
    iron: 0.1,
    vitaminA: 0,
    vitaminC: 0
  },

  // --- POPULAR MEALS, SNACKS & DISHES ---
  {
    id: "pizza_slice",
    names: ["pizza", "slice of pizza", "pizza slice", "cheese pizza", "pepperoni pizza"],
    category: "meals",
    defaultUnit: "slice",
    servingWeightG: 107,
    calories: 272,
    protein: 12.0,
    carbs: 33.0,
    fat: 10.0,
    fiber: 2.3,
    sugar: 3.8,
    sodium: 590,
    potassium: 172,
    calcium: 188,
    iron: 2.3,
    vitaminA: 360,
    vitaminC: 2.5
  },
  {
    id: "burger",
    names: ["burger", "cheeseburger", "chicken burger", "veggie burger"],
    category: "meals",
    defaultUnit: "piece",
    servingWeightG: 220,
    calories: 450,
    protein: 24.0,
    carbs: 40.0,
    fat: 22.0,
    fiber: 3.0,
    sugar: 6.0,
    sodium: 780,
    potassium: 350,
    calcium: 120,
    iron: 3.5,
    vitaminA: 180,
    vitaminC: 4
  },
  {
    id: "sandwich",
    names: ["sandwich", "chicken sandwich", "egg sandwich", "veg sandwich", "club sandwich"],
    category: "meals",
    defaultUnit: "piece",
    servingWeightG: 180,
    calories: 320,
    protein: 16.0,
    carbs: 34.0,
    fat: 13.0,
    fiber: 3.5,
    sugar: 4.2,
    sodium: 620,
    potassium: 260,
    calcium: 110,
    iron: 2.4,
    vitaminA: 140,
    vitaminC: 6
  },
  {
    id: "biryani",
    names: ["biryani", "chicken biryani", "mutton biryani", "veg biryani", "plate of biryani"],
    category: "meals",
    defaultUnit: "plate",
    servingWeightG: 300,
    calories: 480,
    protein: 22.0,
    carbs: 58.0,
    fat: 18.0,
    fiber: 3.8,
    sugar: 3.2,
    sodium: 680,
    potassium: 410,
    calcium: 60,
    iron: 2.8,
    vitaminA: 210,
    vitaminC: 8
  },
  {
    id: "dosa",
    names: ["dosa", "masala dosa", "plain dosa"],
    category: "meals",
    defaultUnit: "piece",
    servingWeightG: 120,
    calories: 168,
    protein: 3.9,
    carbs: 29.0,
    fat: 3.7,
    fiber: 1.4,
    sugar: 0.6,
    sodium: 210,
    potassium: 95,
    calcium: 18,
    iron: 0.9,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "idli",
    names: ["idli", "idlis", "steamed idli", "steamed idlis"],
    category: "meals",
    defaultUnit: "piece",
    servingWeightG: 45,
    calories: 58,
    protein: 2.0,
    carbs: 12.0,
    fat: 0.2,
    fiber: 0.8,
    sugar: 0.2,
    sodium: 110,
    potassium: 45,
    calcium: 12,
    iron: 0.4,
    vitaminA: 0,
    vitaminC: 0
  },
  {
    id: "samosa",
    names: ["samosa", "samosas", "potato samosa"],
    category: "snacks",
    defaultUnit: "piece",
    servingWeightG: 80,
    calories: 260,
    protein: 3.5,
    carbs: 24.0,
    fat: 17.0,
    fiber: 2.1,
    sugar: 1.5,
    sodium: 380,
    potassium: 190,
    calcium: 22,
    iron: 1.3,
    vitaminA: 45,
    vitaminC: 5
  },
  {
    id: "dark_chocolate",
    names: ["dark chocolate", "chocolate", "chocolate piece"],
    category: "snacks",
    defaultUnit: "piece",
    servingWeightG: 20,
    calories: 115,
    protein: 1.5,
    carbs: 11.0,
    fat: 8.5,
    fiber: 2.0,
    sugar: 6.0,
    sodium: 4,
    potassium: 140,
    calcium: 15,
    iron: 2.4,
    vitaminA: 10,
    vitaminC: 0
  }
];

// Unit conversion factors relative to standard default unit
export const UNIT_MULTIPLIERS = {
  "g": 0.01,         // grams (if base is 100g, 100 * 0.01 = 1)
  "gram": 0.01,
  "grams": 0.01,
  "kg": 10.0,
  "ml": 0.00417,     // assuming standard 240ml cup
  "oz": 0.28,
  "cup": 1.0,
  "cups": 1.0,
  "glass": 1.0,
  "glasses": 1.0,
  "bowl": 1.0,
  "bowls": 1.0,
  "plate": 1.0,
  "plates": 1.0,
  "slice": 1.0,
  "slices": 1.0,
  "piece": 1.0,
  "pieces": 1.0,
  "egg": 1.0,
  "eggs": 1.0,
  "medium": 1.0,
  "large": 1.3,
  "small": 0.7,
  "tbsp": 1.0,
  "tablespoon": 1.0,
  "tablespoons": 1.0,
  "tsp": 0.33,
  "teaspoon": 0.33,
  "teaspoons": 0.33,
  "scoop": 1.0,
  "scoops": 1.0,
  "handful": 1.0,
  "can": 1.0,
  "bottle": 2.0
};
